# Generated by Django 3.0.10 on 2020-10-19 16:09

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='', help_text='封面1', upload_to=home.models.image_file_path)),
                ('image2', models.ImageField(blank=True, default='', help_text='封面2', upload_to=home.models.image_file_path)),
                ('image3', models.ImageField(blank=True, default='', help_text='封面3', upload_to=home.models.image_file_path)),
                ('image4', models.ImageField(blank=True, default='', help_text='封面4', upload_to=home.models.image_file_path)),
                ('image5', models.ImageField(blank=True, default='', help_text='封面5', upload_to=home.models.image_file_path)),
            ],
        ),
    ]
