# Generated by Django 3.0.10 on 2020-11-10 10:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='姓名', max_length=200)),
                ('title', models.CharField(default='', help_text='主旨', max_length=200)),
                ('email', models.CharField(default='', help_text='信箱', max_length=200)),
                ('phone', models.CharField(default='', help_text='手機', max_length=200)),
                ('message', models.CharField(default='', help_text='訊息', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(blank=True, default='', help_text='封面1 寬:450px 高:450px', upload_to=home.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(blank=True, default='', help_text='封面2 寬:450px 高:450px', upload_to=home.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image3',
            field=models.ImageField(blank=True, default='', help_text='封面3 寬:450px 高:450px', upload_to=home.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image4',
            field=models.ImageField(blank=True, default='', help_text='封面4 寬:450px 高:450px', upload_to=home.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image5',
            field=models.ImageField(blank=True, default='', help_text='封面5 寬:450px 高:450px', upload_to=home.models.image_file_path),
        ),
    ]
