version: "3.7"

services:
    fetus:
      build:
        context: .
      volumes:
       - ./fetus:/fetus
       - static_data:/vol/web
      environment:
        - DB_HOST=db
        - DB_NAME=fetus
        - DB_USER=postgres
        - DB_PASS=supersecretpassword
        - ALLOWED_HOSTS=127.0.0.1,localhost
        - DJANGO_SECRET_KEY=djk65das
        - EMAIL_ACCOUNT=andyfamrykames@gmail.com
        - EMAIL_PASSWORD=jks86311202
      depends_on:
        - db

    proxy:
        build:
          context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8000:8000"
            - "8001:8001"   # 重導用 Nginx 監聽埠
        depends_on:
            - fetus
        environment:
            - LISTEN_PORT=8000
            - APP_HOST=fetus
            - APP_PORT=9000
            - SERVER_NAME=yuan-pei.com

    db:
      image: postgres:12-alpine
      volumes:
        - fetus_postgres_data:/var/lib/postgresql/data  # <--- 使用新的 Named Volume
      environment:
        - POSTGRES_DB=fetus
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword
      # 如果您的 PostgreSQL 需要特定的啟動參數或設定檔，可以在這裡添加
      restart: unless-stopped # 建議加上，容器意外停止會自動重啟


volumes:
    fetus_postgres_data: {} # 新的資料庫 named volume
    static_data: