# Generated by Django 3.0.10 on 2020-10-19 16:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', help_text='手機或電話', max_length=200)),
                ('adress', models.CharField(default='', help_text='公司地址', max_length=200)),
                ('email', models.EmailField(default='', help_text='公司信箱', max_length=100)),
                ('year', models.CharField(default='', help_text='今年年分', max_length=10)),
                ('home_bg', models.ImageField(blank=True, default='', help_text='主頁背景', upload_to=core.models.image_file_path)),
                ('work_bg', models.ImageField(blank=True, default='', help_text='作品分類背景', upload_to=core.models.image_file_path)),
                ('work_list_bg', models.ImageField(blank=True, default='', help_text='作品列表背景', upload_to=core.models.image_file_path)),
                ('service_bg', models.ImageField(blank=True, default='', help_text='服務背景', upload_to=core.models.image_file_path)),
                ('about_bg', models.ImageField(blank=True, default='', help_text='關於我背景', upload_to=core.models.image_file_path)),
                ('contact_bg', models.ImageField(blank=True, default='', help_text='聯絡我背景', upload_to=core.models.image_file_path)),
            ],
        ),
    ]
