# Generated by Django 3.0.11 on 2020-11-23 14:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201122_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='about_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='關於我 下方文字顏色', max_length=18),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='about_title_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='關於我 下方標題選擇顏色', max_length=18),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='網頁最下方文字顏色(@2020~)', max_length=18),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='service_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='服務 下方文字顏色', max_length=18),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='service_title_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='服務 下方標題文字顏色', max_length=18),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='works_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='作品分類 下方選擇顏色', max_length=18),
        ),
    ]
