# Generated by Django 3.0.11 on 2021-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201125_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='home_bg_position',
            field=models.CharField(default='50%', help_text='背景位置 例:10%', max_length=200),
        ),
    ]
