# Generated by Django 3.0.10 on 2020-10-19 16:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='照片標題(例:案子名稱_臥室1...)', max_length=200)),
                ('image', models.ImageField(help_text='照片', upload_to=projects.models.image_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', help_text='案子類別(自己看的分類)', max_length=20)),
                ('c_title', models.CharField(default='', help_text='中文名子(顯示在作品列表)', max_length=30)),
                ('e_title', models.CharField(default='', help_text='英文名子(顯示在作品列表)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(default='', help_text='中文標題', max_length=30)),
                ('e_title', models.CharField(default='', help_text='英文標題', max_length=30)),
                ('preview_img', models.ImageField(default='', help_text='外部顯示圖片', upload_to=projects.models.preview_img_file_path)),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='案子文字敘述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建日期')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日期')),
                ('images', models.ManyToManyField(help_text='案子照片(複選) 按住ctrl複選', to='projects.ImageInfo')),
                ('project_tag', models.ForeignKey(default='', help_text='案子類別', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_tag', to='projects.Tags')),
            ],
        ),
    ]
