# Generated by Django 3.0.11 on 2020-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201110_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lock',
            field=models.BooleanField(default=False, help_text='隱藏專案'),
        ),
    ]
